## remember these values are base64 encoded , the person who can access this secret.yml file can easily decode these values if he want. 
#
## recommended to used AWS secret manager or vault for real life production project 


apiVersion: v1
kind: Secret
metadata: 
  name: db-credentials 
  namespace: project

type: Opaque 
data:
  DB_USER: YXBwdXNlcg==
  DB_PASSWORD: YXBwcGFzc3dvcmQxMjM=
  DB_NAME: YXBwZGI= 
