name: CICD build and deploy
on:
  push:
    branches:
      - main 
    paths:
      - "app/**"
      - "k8s/**"
      - ".github/workflows/deploy.yml"

  workflow_dispatch: 
env:
  IMAGE_NAME: backend_app
  CLUSTER_NAME: project
  NAMESPACE: project

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image 
        run: | 
          docker build -t ${{ env.IMAGE_NAME }}:latest .
      - name: Load image to the kind cluster 
        run: kind load docker-image ${{env.IMAGE_NAME}}:latest --name project
      - name: Ensure correct kube context \
        run: kubectl config use-context kind-${{env.CLUSTER_NAME}}

      - name: Apply base manifests 
        run: | 
          cd k8s
          kubectl apply -f namespace.yml 
          kubectl apply -f secret.yml 
          kubectl apply -f postgres_pvc_claim.yml 
          kubectl apply -f postgres_deployment.yml 
          kubectl apply -f postgres_service.yml 
          kubectl apply -f backend_dep.yml 
          kubectl apply -f backend-service.yml
      # rollout: Updating to the latest version : automatically latest version gonna be used in the pods containers background: 
        # rollout basically depends on the type of deployment strategy mainly ROLLINGUPDATE 
      - name: wait for rollout to complete 
        run: | 
          kubectl rollout status deployment/backend -n ${{ env.NAMESPACE }} --timeout=120s 

      - name: Post deployment verification
        run: | 
          echo "------PODS--------"
          kubectl get pods -n ${{env.NAMESPACE}} -o wide 
          echo "ROLLOUT history"
          kubectl rollout history deployment/backend -n ${{ env.NAMESPACE }}
          echo "--- Smoke test ---"
          kubectl run smoke-test --rm -i --restart=Never --image=curlimages/curl -n ${{ env.NAMESPACE }}
          curl -sf http://backend:8080/ready || (echo "SMOKE TEST FAILED"; exit 1)
          

          
          
